stores:
    fastfetch:
        target: ~/.config/fastfetch
    ghostty:
        target: ~/.config/ghostty
    niri:
        target: ~/.config/niri
    noctalia:
        target: ~/.config/noctalia
    wireplumber:
        target: ~/.config/wireplumber
