access.permission-managers = [
  {
    name = "discord-game-capture-blacklist"
    default_permissions = "all"
    core_permissions = "rx"
    rules = [
      {
        matches = [
          {
            application.name = "TeamSpeak"
          }
          {
            application.name = "Spotify"
          }
          {
            application.name = "Google Chrome"
          }
          {
            # Blocks discord mute/unmute sounds & notifcations
            application.name = "Chromium"
          }
        ]
        actions = {
          set-permissions = "-"
        }
      }
    ]
  }
]


access.rules = [
  {
    matches = [
      {
        application.name = "discord_capture"
      }
    ]
    actions = {
      update-props = {
        permission_manager_name = "discord-game-capture-blacklist"
      }
    }
  }
]

